E-Commerce Website/Controllers/AdminController.cs
using E_Commerce_Website.DAL.Constant;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace E_Commerce_Website.Controllers
{
    [Authorize(Roles = Roles.adminrole)]
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

E-Commerce Website/Controllers/CommentsController.cs
using E_Commerce_Website.BL.IRepositories;
using E_Commerce_Website.BL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace E_Commerce_Website.Controllers
{
    [Authorize]
    public class CommentsController : Controller
    {
        private readonly IServiceComments serviceComments;
        public CommentsController(IServiceComments serviceComments)
        {
            this.serviceComments = serviceComments;
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(CommentViewModel comment)
        {
            if (ModelState.IsValid)
            {
                var name = User.Identity.Name;
                comment.UserName = name;
                await serviceComments.AddComment(comment);
            }
            return RedirectToAction("ShowDetailes", "ShowMenu", new { Id = comment.ProductId });
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int commentId,int productID)
        {
            if (commentId > 0)
            {
                await serviceComments.DeleteComment(commentId);
            }
            return RedirectToAction("ShowDetailes", "ShowMenu", new { Id = productID});
        }
    }
}

E-Commerce Website/Controllers/OrderController.cs
using E_Commerce_Website.BL.IRepositories;
using E_Commerce_Website.BL.Pagination;
using E_Commerce_Website.BL.ViewModels;
using E_Commerce_Website.DAL.Constant;
using E_Commerce_Website.DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace E_Commerce_Website.Controllers
{
    public class OrderController : Controller
    {
        private readonly IServiceOrder serviceOrder;
        private readonly IServiceFinishOrder serviceFinishedOrder;

        public OrderController(IServiceOrder serviceOrder, IServiceFinishOrder serviceFinishedOrder)
        {
            this.serviceOrder = serviceOrder;
            this.serviceFinishedOrder = serviceFinishedOrder;
        }
        [Authorize(Roles = Roles.userrole)]
        public async Task<IActionResult> AddOrder()
        {
            string name = User.Identity.Name;
            if (name is not null)
            {
                var list = await serviceOrder.CheckoutOrder(name);
                ViewBag.totalprice = await serviceOrder.totalprice(name);
                return View(list);
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrder(OrderViewModel orderViewModel)
        {
            if (ModelState.IsValid)
            {
                await serviceOrder.AddOrder(orderViewModel);
                return RedirectToAction("ShowOrders");
            }
            return View(orderViewModel);
        }
        [HttpGet]
        public async Task<IActionResult> ShowOrders(int pg=1)
        {
            string name = User.Identity.Name;
            ViewBag.list = await serviceOrder.Order(name);
            var listorders = await serviceFinishedOrder.GetAllFinishedOrderByName(name);
            var data = Pagination<FinishedOrders>.GetPaginationData(pg, listorders);
            this.ViewBag.Pager = data.Item2;
            return View(data.Item1);
        }
    }
}

E-Commerce Website/Controllers/ProfileController.cs
using E_Commerce_Website.DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace E_Commerce_Website.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        public ProfileController(UserManager<ApplicationUser> userManager)
        {
            this.userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            string name = User.Identity.Name;
            ApplicationUser user = await userManager.FindByNameAsync(name);
            if (user is not null)
            {
                return View(user);
            }

            return View();
        }
    }
}

E-Commerce Website/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <title>dashboard</title>

     <link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css" />

   <!-- font awesome cdn link  -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
   
   <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
   <!-- custom css file link  -->
   <link rel="stylesheet" href="~/css/edit-style.css">
   <style>
       body{
           background-color:orange;
       }
       .logo a{
      font-size: 25px;
      color:black;
      margin-left:100px;
      margin-top:10px;
      text-decoration:underline;
   }
.logo a:hover{
    color:orangered;
       }
        #content
        {
           flex-grow: 1;
           width:100%;
           height:100%;
           margin:0 auto;
           overflow: auto; 
           font-size:16px;
        }
   </style>
    @await RenderSectionAsync("stylecss", required: false)
</head>
<body>
<div class="logo">
      <a asp-controller="Home" asp-action="Index" class="logo">Shopie<span>.</span></a>
</div>
<section class="container container-fluid">
    @RenderBody()
</section>


<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery-easing/jquery.easing.min.js"></script>
<script src="https://unpkg.com/swiper@8/swiper-bundle.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/admin_script.js"></script>
 @await RenderSectionAsync("Scripts", required: false)
 </body>
</html>

E-Commerce Website/Views/Shared/_CommentBox.cshtml
@model CommentViewModel

 <dl class="dl-horizontal">
            <dt style="font-size:25px;font-weight:700">
                Comment
            </dt>
            <dd>
              <div class="commentBox">
                 
                    <form asp-action="Add" asp-controller="Comments" onsubmit="return SubmitComment()">
                         <div class="form-horizontal">
                            <div class="form-group">
                                <label class=" control-label mb-2">Rating This Product
                                </label>
                                <div class="col-md-7">
                                    <div onmouseout="CRateSelected()">
                                        <span class="starFade" id="Rate1" onclick="CRate(1)" onmouseover="CRateOver(1)" onmouseout="CRateOut(1)"></span>
                                        <span class="starFade" id="Rate2" onclick="CRate(2)" onmouseover="CRateOver(2)" onmouseout="CRateOut(2)"></span>
                                        <span class="starFade" id="Rate3" onclick="CRate(3)" onmouseover="CRateOver(3)" onmouseout="CRateOut(3)"></span>
                                        <span class="starFade" id="Rate4" onclick="CRate(4)" onmouseover="CRateOver(4)" onmouseout="CRateOut(4)"></span>
                                        <span class="starFade" id="Rate5" onclick="CRate(5)" onmouseover="CRateOver(5)" onmouseout="CRateOut(5)"></span>
                                    </div>
                                </div>
                            </div>
                         </div>
                         <div class="form-group">
                             <div class="col-12">
                               <textarea asp-for="Comments" required rows="5" style="width:100%;font-size:16px" class="form-control"></textarea>
                             </div>
                         </div>
                        <input type="hidden" asp-for="ProductId"value="@ViewData["ProductId"]"/>
                        <input type="hidden" name="Rating" id="Rating" value="0" />
                        
                        <button type="submit" id="btnRegister" name="btnRegister" class="btn col-8">Add Comment </button>
                    </form>
              </div>
            </dd>
        </dl>
    <script>
        function SubmitComment()
        {
            if ($("#Rating").val() == "0") 
            {
                alert("Please Rate this Product");
                return false;
            }
            else 
            {
                return true;
            }
        }
        function CRate(r) 
        {
            $("#Rating").val(r);
            for (var i = 1; i <= r;i++)
            {
                $("#Rate" + i).attr('class', 'starGlow');
            }
            for (var i =r+ 1; i <= 5;i++)
            {
                $("#Rate" + i).attr('class', 'starFade');
            }
        }
       function CRateOver(r) 
       {
            for (var i = 1; i <= r;i++)
            {
                $("#Rate" + i).attr('class', 'starGlow');
            }
        }
         function CRateOut(r) 
         {
            for (var i = 1; i <= r;i++)
            {
                $("#Rate" + i).attr('class', 'starFade');
            }
        }
         function CRateSelected(r) 
         {
             var setRating = $("#Rating").val();
            for (var i = 1; i <= setRating;i++)
            {
                $("#Rate" + i).attr('class', 'starGlow');
            }
        }
    </script>
    @section Scripts{
    <partial name="_ValidationScriptsPartial" />
   } 

E-Commerce Website/Views/Shared/_Layout.cshtml
@{
 @using E_Commerce_Website.BL.Repositories
 @inject IServiceWishList serviceWish
 var countWish=await serviceWish.GetWishListCount(User.Identity.Name);
 @inject IServiceCart serviceCart
 var countCart=await serviceCart.GetCartCount(User.Identity.Name);
}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <title>@ViewData["Title"] - E-Commerce</title>

     <link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css" />

   <!-- font awesome cdn link  -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
   <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/style.css">
    @await RenderSectionAsync("stylecss", required: false)
</head>
<body>
    
<!-- header section starts  -->

<header class="header">

   <section class="flex">

      <a asp-controller="Home" asp-action="Index" class="logo">Shopie<span>.</span></a>

      <nav class="navbar">
         <a asp-controller="Home" asp-action="Index">home</a>
         <a asp-controller="Home" asp-action="About">about</a>
         <a asp-controller="Order" asp-action="ShowOrders">orders</a>
         <a asp-controller="ShowMenu" asp-action="Index">shop</a>
         <a asp-controller="Home" asp-action="Contact">contact</a>
         @if(@User.IsInRole(Roles.adminrole))
         {
          <a asp-action="Index" asp-controller="Admin">Admin</a>
         }
      </nav>

      <div class="icons">
       
         <div id="menu-btn" class="fas fa-bars"></div>
         <a asp-controller="ShowMenu" asp-action="SearchMenu"><i class="fas fa-search"></i></a>
         <a asp-controller="WishList" asp-action="Index"><i class="fas fa-heart"></i><span>@countWish</span></a>
         <a asp-controller="Cart" asp-action="Index"><i class="fas fa-shopping-cart"></i><span>@countCart</span></a>
         <div id="user-btn" class="fas fa-user"></div>
      </div>

      <div class="profile">
         @if(User.Identity.IsAuthenticated==true)
          {
         <p>@User.Identity.Name</p>
         <a asp-controller="Profile" asp-action="Index" class="btn">profile</a>
        
         <a asp-controller="Account" asp-action="Logout" class="delete-btn" onclick="return confirm('logout from the website?');">logout</a> 
          }
          else
          {
         <p>please login or register first!</p>
         <div class="flex-btn">
            <a asp-controller="Account" asp-action="Registration" class="option-btn">register</a>
            <a asp-controller="Account" asp-action="Login" class="option-btn">login</a>
         </div>
          }
         
         
      </div>

   </section>

</header>

<!-- header section ends -->

<!-- side-bar section starts -->


<!-- home section starts  -->

@RenderBody()




<!-- footer section starts  -->
<footer class="footer">

   <section class="grid">

      <div class="box">
         <h3>quick links</h3>
         <a asp-controller="Home" asp-action="Index"> <i class="fas fa-angle-right"></i> home</a>
         <a asp-controller="Home" asp-action="About"> <i class="fas fa-angle-right"></i> about</a>
         <a asp-controller="ShowOrder" asp-action="Index"> <i class="fas fa-angle-right"></i> shop</a>
         <a asp-controller="Home" asp-action="Contact"> <i class="fas fa-angle-right"></i> contact</a>
      </div>

      <div class="box">
         <h3>extra links</h3>
         <a asp-controller="Account" asp-action="Login"> <i class="fas fa-angle-right"></i> login</a>
         <a asp-controller="Account" asp-action="Register"> <i class="fas fa-angle-right"></i> register</a>
         <a asp-controller="Cart" asp-action="Index"> <i class="fas fa-angle-right"></i> cart</a>
         <a asp-controller="Order" asp-action="ShowOrders"> <i class="fas fa-angle-right"></i> orders</a>
      </div>

      <div class="box">
         <h3>contact us</h3>
         <a href="tel:1234567890"><i class="fas fa-phone"></i>+20 01054655473</a>
         <a href="tel:11122233333"><i class="fas fa-phone"></i>+20 01112546734</a>
         <a href="mailto:www.michael.m.s.com@gmail.com"><i class="fas fa-envelope"></i> michaelsoft.com</a>
         <a href="https://www.google.com/myplace"><i class="fas fa-map-marker-alt"></i> minya, Egypt </a>
      </div>

      <div class="box">
         <h3>follow us</h3>
         <a href="#"><i class="fab fa-facebook-f"></i>facebook</a>
         <a href="#"><i class="fab fa-twitter"></i>twitter</a>
         <a href="#"><i class="fab fa-instagram"></i>instagram</a>
      </div>

   </section>

   <div class="credit">&copy; copyright 2023> by <span>MichaelSoft</span> | all rights reserved!</div>

</footer>


<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery-easing/jquery.easing.min.js"></script>
<script src="https://unpkg.com/swiper@8/swiper-bundle.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

<script src="~/js/script.js" asp-append-version="true"></script>


@await RenderSectionAsync("Scripts", required: false)

</body>
</html>