E-Commerce Website/Controllers/AdminController.cs
using E_Commerce_Website.DAL.Constant;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace E_Commerce_Website.Controllers
{
    [Authorize(Roles = Roles.adminrole)]
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

E-Commerce Website/Controllers/CategoryController.cs
using E_Commerce_Website.BL.IRepositories;
using E_Commerce_Website.BL.Pagination;
using E_Commerce_Website.BL.Search;
using E_Commerce_Website.BL.ViewModels;
using E_Commerce_Website.DAL.Constant;
using E_Commerce_Website.DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace E_Commerce_Website.Controllers
{
        [Authorize(Roles = Roles.adminrole)]
        public class CategoryController : Controller
        {
            private readonly IServiceCategory serviceCategory;
           public CategoryController(IServiceCategory serviceCategory)
            {
                this.serviceCategory = serviceCategory;
            }
            #region all categories
            public async Task<IActionResult> Index(string search, int pg=1)
            {
                List<Categories> Categorylist = await serviceCategory.GetallCategories();
                if(search is not null)
                {
                    var searchData = Search<Categories>.SearchByName(pg, search, Categorylist);
                    this.ViewBag.Pager = searchData.Item2;
                    return View(searchData.Item1);
                }
                var data = Pagination<Categories>.GetPaginationData(pg, Categorylist);
                this.ViewBag.Pager = data.Item2;
                return View(data.Item1);
            }

            #endregion


            #region  deleted categories
            [HttpGet]
            public async Task<IActionResult> DeletedCategory(string search,int pg=1)
            {
                var Categorylistdeleted = await serviceCategory.GetalldeletedCategories();
                if (search is not null)
                {
                    var searchData = Search<Categories>.SearchByNameDelete(pg, search, Categorylistdeleted);
                    this.ViewBag.pager = searchData.Item2;
                    return View(searchData.Item1);
                }
                var data = Pagination<Categories>.GetPaginationData(pg, Categorylistdeleted);
                this.ViewBag.pager = data.Item2;
                return View(data.Item1);
            }

            #endregion

            #region  create categories
            [HttpGet]
            public IActionResult CreateCategory()
            {
                return View();
            }

            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> CreateCategory(CategoryViewModel categoryViewModel)
            {

                if (ModelState.IsValid)
                {
               var name = User.Identity.Name;
                var result = await serviceCategory.add(categoryViewModel,name);
                    return RedirectToAction("Index");
                }

                return View(categoryViewModel);
            }

            #endregion

            #region  updated categories

            [HttpGet]
            public async Task<IActionResult> UpdateCategory(int Id)
            {
                var result = await serviceCategory.GetByid(Id);
                return View(result);
            }

            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> UpdateCategory(CategoryUpdateViewModel categoryUpdateViewModel)
            {
                if (ModelState.IsValid)
                {
                var name = User.Identity.Name;
                await serviceCategory.Update(categoryUpdateViewModel,name);
                    return RedirectToAction("Index");
                }
                return View(categoryUpdateViewModel);
            }

            #endregion

            #region  deleted categories

            [HttpGet]
            public async Task<IActionResult> DeleteCategory(int Id)
            {
                var name = User.Identity.Name;
                await serviceCategory.Delete(Id,name);
                return RedirectToAction("Index");
            }

            #endregion


            #region restore categories

            [HttpGet]
            public async Task<IActionResult> RestoreCategory(int Id)
            {
                var name = User.Identity.Name;
                await serviceCategory.RestoreCategory(Id,name);
                return RedirectToAction("DeletedCategory");
            }

            #endregion
        }
    
}

E-Commerce Website/Views/Category/CreateCategory.cshtml
@model CategoryViewModel
@{
    ViewData["Title"] = "Create";
    Layout = "_AdminLayout";
}
@section stylecss{
    <style>
        span{
            font-size:14px;
        }
    </style>
}
<section class="form-container">

   <form asp-action="CreateCategory" asp-controller="Category">
       <div asp-validation-summary="All" class="text-danger" style="font-size:14px;"></div>
       <div class="input-group">
           <label asp-for="Name" style="font-size:15px"></label>
           <input type="text" asp-for="Name" maxlength="25" minlength="5" placeholder="enter name" class="box" autofocus>
       </div>
       
       <input type="submit" value="Create" class="btn btn-success" name="submit">
   </form>

</section>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

E-Commerce Website/Views/Category/DeletedCategory.cshtml
@model List< Categories>
@{
    ViewData["Title"] = "Deleted Categories";
    Layout = "_AdminLayout";
     Pager pager=new Pager();
    int pageNo=0;
    if(ViewBag.pager is not null)
    {
        pager = ViewBag.pager;
        pageNo = pager.CurrentPage;
    }
}
<div style="margin-top:30px">
              <div class="flex-flow justify-content-start input-group mb-4">
                 <a asp-action="Index" asp-controller="Admin" class="btn btn-secondary" style="margin-right:6rem">Back to Dashboard</a>
              </div>
            <div class="flex-flow mb-1">
                  <form asp-action="DeletedCategory" method="get">
              <div class="input-group justify-content-end">
                 <div class="form-outline">
                     <input type="search" id="form1" name="search" class="form-control" />
                  </div>
                  <button type="submit" value="search" class="btn btn-primary">
                      <i class="fas fa-search"></i>
                  </button>
                  <a asp-action="DeletedCategory" asp-controller="Category" class="btn btn-primary" style="margin-left:6rem">Refresh</a>
              </div>
            </form>
             </div>
     
    <div id="content" >
        <table class="table table-bordered mt-3">
            <thead class=" text-center" style="background:#2b6777 ;color:white">
                <tr style="margin:auto">
                    <th>Code</th>
                    <th>Name</th>
                    <th>UserName</th>
                    <th>Create Date</th>
                    <th>Update Date</th>
                    <th>Delete Date</th>
                    <th>Restore Date</th>
                    <th>Is Deleted</th>
                    <th>Options</th>
                </tr>
             </thead>
             <tbody class="m-1">
               @foreach(var itm in Model)
                {
                    <tr style="margin:auto">
                        <td>@itm.Id</td>
                        <td>@itm.Name</td>
                        <td>@itm.UserName</td>
                        <td>@itm.CreateDate</td>                        
                        <td>@itm.UpdateDate</td>
                        <td>@itm.DeleteDate</td>
                        <td>@itm.RestoreDate</td>
                        <td>@itm.IsDeleted</td>
                        <td>
                            <a asp-action="RestoreCategory" id="btn" asp-controller="Category"asp-route-id="@itm.Id"onclick="return confirm('are you sure to restore this item @itm.Name')" class="btn btn-danger">Restore</a>

                        </td>
                    </tr>
        
                }
            </tbody>
        </table>
         <nav class="...">
            @if(pager.TotalPages>0)
            {
                <ul class="pagination justify-content-center pagination-lg">
                    @if(pager.CurrentPage>1)
                    {
                        <li class="page-item">
                            <a class="page-link"asp-action="DeletedCategory" asp-controller="Category" asp-route-pg="1">Frist</a>
                        </li>  
                        <li>
                            <a class="page-link"asp-action="DeletedCategory" asp-controller="Category" asp-route-pg="@(pager.CurrentPage-1)">Previous</a>
                        </li>
                    }
                    @for(var pge =pager.StartPage;pge <= pager.EndPage;pge++)
                    {
                        <li class="page-item" @(pge==pager.CurrentPage? "active" :"")>
                            <a class="page-link"asp-action="DeletedCategory" asp-controller="Category" asp-route-pg="@pge">@pge</a>
                        </li>
                    }
                    @if(pager.CurrentPage<pager.TotalPages)
                    {
                       <li class="page-item">
                            <a class="page-link"asp-action="DeletedCategory" asp-controller="Category" asp-route-pg="@(pager.CurrentPage+1)">Next</a>
                        </li> 
                        <li class="page-item">
                            <a class="page-link"asp-action="DeletedCategory" asp-controller="Category" asp-route-pg="@(pager.TotalPages)">Last</a>
                        </li> 
                    }

                </ul>
            }
        </nav>
    </div>
</div>

E-Commerce Website/Views/Category/Index.cshtml
@model List< Categories>
@{
    ViewData["Title"] = "Categories";
    Layout = "_AdminLayout";
    Pager pager=new Pager();
    int pageNo=0;
    if(ViewBag.Pager is not null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}

<div style="margin-top:30px">
                <div class="flex-flow justify-content-start input-group mb-4">
                    <a asp-action="Index" asp-controller="Admin" class="btn btn-secondary" style="margin-right:6rem">Back to Dashboard</a>
                     <a asp-action="CreateCategory" asp-controller="Category" class="btn btn-success" style="margin-right:6rem">Create</a>
                </div>
                <div class="flex-flow mb-1">
                  <form asp-action="Index" method="get">
                   <div class="input-group justify-content-end">
                
                 <div class="form-outline">
                     <input type="search" id="form1" name="search" class="form-control" />
                  </div>
                  <button type="submit" value="search" class="btn btn-primary">
                      <i class="fas fa-search"></i>
                  </button>
                  <a asp-action="Index" asp-controller="Category" class="btn btn-primary" style="margin-left:6rem">Refresh</a>
              </div>
            </form>  
                </div>
            
    <div id="content" >
        <table class="table table-bordered mt-3">
            <thead class=" text-center" style="background:#2b6777 ;color:white">
                <tr style="margin:auto">
                     <th>Code</th>
                     <th>Name</th>
                     <th>Is Deleted</th>
                      <th>UserName</th>
                      <th>Create Date</th>
                      <th>Update Date</th>
                      <th>Delete Date</th>
                      <th>Restore Date</th>
                     <th>Options</th>
                 </tr>
             </thead>
             <tbody class="m-1">
               @foreach(var itm in Model)
                {
                    <tr style="margin:auto">
                        <td>@itm.Id</td>
                        <td>@itm.Name</td>                       
                        <td>@itm.IsDeleted</td>
                        <td>@itm.UserName</td>
                         <td>@itm.CreateDate</td>
                        <td>@itm.UpdateDate</td>
                        <td>@itm.DeleteDate</td>
                        <td>@itm.RestoreDate</td>
                        <td>
                            <a asp-action="UpdateCategory" id="btn" asp-controller="Category" asp-route-id="@itm.Id"class="btn btn-secondary m-1">Edit</a>
                            <a asp-action="DeleteCategory" id="btn" asp-controller="Category"asp-route-id="@itm.Id"onclick="return confirm('are you sure to delete this item @itm.Name')" class="btn btn-danger m-1">Delete</a>
                        </td>
                    </tr>
        
                }
            </tbody>
        </table>
        <nav class="...">
            @if(pager.TotalPages>0)
            {
                <ul class="pagination justify-content-center pagination-lg">
                    @if(pager.CurrentPage>1)
                    {
                        <li class="page-item">
                            <a class="page-link"asp-action="Index" asp-controller="Category" asp-route-pg="1">Frist</a>
                        </li>  
                        <li>
                            <a class="page-link"asp-action="Index" asp-controller="Category" asp-route-pg="@(pager.CurrentPage-1)">Previous</a>
                        </li>
                    }
                    @for(var pge =pager.StartPage;pge <= pager.EndPage;pge++)
                    {
                        <li class="page-item" @(pge==pager.CurrentPage? "active" :"")>
                            <a class="page-link"asp-action="Index" asp-controller="Category" asp-route-pg="@pge">@pge</a>
                        </li>
                    }
                    @if(pager.CurrentPage<pager.TotalPages)
                    {
                       <li class="page-item">
                            <a class="page-link"asp-action="Index" asp-controller="Category" asp-route-pg="@(pager.CurrentPage+1)">Next</a>
                        </li> 
                        <li class="page-item">
                            <a class="page-link"asp-action="Index" asp-controller="Category" asp-route-pg="@(pager.TotalPages)">Last</a>
                        </li> 
                    }

                </ul>
            }
        </nav>
    </div>
    
</div>

E-Commerce Website/Views/Category/UpdateCategory.cshtml
@model CategoryUpdateViewModel
@{
    ViewData["Title"] = "Update";
    Layout = "_AdminLayout";
}
@section stylecss{
    <style>
        span{
            font-size:14px;
        }
    </style>
}
<section class="form-container">

   <form asp-action="UpdateCategory" asp-controller="Category">
       <div asp-validation-summary="All" class="text-danger" style="font-size:14px;"></div>
       <input type="hidden" asp-for="Id" />
       <div class="input-group">
           <label asp-for="Name" style="font-size:15px"></label>
           <input type="text" asp-for="Name" maxlength="25" minlength="5" value="@Model.Name" placeholder="enter name" class="box" autofocus>
       </div>       
       <input type="submit" value="Update" class="btn btn-success" name="submit">
   </form>

</section>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}