E-Commerce Website/Controllers/AdminController.cs
using E_Commerce_Website.DAL.Constant;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace E_Commerce_Website.Controllers
{
    [Authorize(Roles = Roles.adminrole)]
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

E-Commerce Website/Controllers/FinishedOrderController.cs
using E_Commerce_Website.BL.IRepositories;
using E_Commerce_Website.BL.Pagination;
using E_Commerce_Website.DAL.Constant;
using E_Commerce_Website.DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace E_Commerce_Website.Controllers
{
    [Authorize(Roles = Roles.adminrole)]
    public class FinishedOrderController : Controller
    {
        private readonly IServiceFinishOrder serviceFinishedOrder;
        public FinishedOrderController(IServiceFinishOrder serviceFinishedOrder)
        {
            this.serviceFinishedOrder = serviceFinishedOrder;
        }

        public async Task<IActionResult> Index(int pg=1)
        {
            var listorders = await serviceFinishedOrder.GetAllFinishedOrder();
            var data = Pagination<FinishedOrders>.GetPaginationData(pg, listorders);
            this.ViewBag.Pager = data.Item2;
            return View(data.Item1);
        }
        [HttpGet]
        public async Task<IActionResult> AddFinishedOrder(int Id)
        {
            await serviceFinishedOrder.AddFinishedOrder(Id);
            return RedirectToAction("Index", "RequestOrder");
        }
    }
}

E-Commerce Website/Controllers/RequestOrderController.cs
using E_Commerce_Website.BL.IRepositories;
using E_Commerce_Website.BL.Pagination;
using E_Commerce_Website.DAL.Constant;
using E_Commerce_Website.DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace E_Commerce_Website.Controllers
{
    [Authorize(Roles = Roles.adminrole)]
    public class RequestOrderController : Controller
    {
        private readonly IServiceOrder serviceOrder;

        public RequestOrderController(IServiceOrder serviceOrder)
        {
            this.serviceOrder = serviceOrder;
        }
        public async Task<IActionResult> Index(int pg=1)
        {
            var listorders = await serviceOrder.AllOrders();
            var data = Pagination<Orders>.GetPaginationData(pg, listorders);
            this.ViewBag.Pager = data.Item2;
            return View(data.Item1);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteOrder(int Id)
        {
            await serviceOrder.DeleteOrder(Id);
            return RedirectToAction("Index");
        }
    }
}

E-Commerce Website/Views/RequestOrder/Index.cshtml
@model List<Orders>
@{
    ViewData["Title"] = "Request Orders";
    Layout = "_AdminLayout";
      Pager pager=new Pager();
    int pageNo=0;
    if(ViewBag.Pager is not null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}
<div style="margin-top:30px">
     <div class="input-group justify-content-center mb-3">     
         <a asp-action="Index" asp-controller="Admin" class="btn btn-secondary" style="margin-right:6rem">Back to Dashboard</a>
        <a asp-action="Index" asp-controller="RequestOrder" class="btn btn-primary"style="margin-right:6rem">Refresh</a>
     </div>
    <div id="content" >
        <table class="table table-bordered mt-3 table-striped table-hover">
            <thead class=" text-center" style="background:#2b6777 ;color:white">
                <tr style="margin:auto">
                     <th>Code</th>
                     <th>Order Detailes</th>
                     <th>Total Price</th>
                     <th>Name</th>
                     <th>Address</th>
                     <th>Phone Number</th>
                     <th>Email</th>
                     <th>Date and Time</th>  
                     <th>State</th> 
                     <th>Options</th>
                 </tr>
             </thead>
             <tbody class="m-1">
               @foreach(var itm in Model)
                {
                    <tr style="margin:auto">
                        <td>@itm.Id</td>
                        <td>@itm.OrderDetails</td>
                        <td>@itm.TotalPrice</td>
                        <td>@itm.Username</td>
                        <td>@itm.AddressDetailes</td>
                        <td>@itm.Phonenumber</td>
                        <td>@itm.Email</td>
                         <td>@itm.Date</td>
                          <td>Pending</td>
                        <td>
                            <a asp-action="AddFinishedOrder"  asp-controller="FinishedOrder" asp-route-id="@itm.Id"class="btn btn-secondary m-1">Accept Order</a>
                            <a asp-action="DeleteOrder"  asp-controller="RequestOrder"asp-route-id="@itm.Id"onclick="return confirm('are you sure to delete this item @itm.Username')" class="btn btn-danger m-1">Delete</a>
                        </td>
                    </tr>
        
                }
            </tbody>
        </table>
         <nav class="...">
            @if(pager.TotalPages>0)
            {
                <ul class="pagination justify-content-center pagination-lg">
                    @if(pager.CurrentPage>1)
                    {
                        <li class="page-item">
                            <a class="page-link"asp-action="Index" asp-controller="RequestOrder" asp-route-pg="1">Frist</a>
                        </li>  
                        <li>
                            <a class="page-link"asp-action="Index" asp-controller="RequestOrder" asp-route-pg="@(pager.CurrentPage-1)">Previous</a>
                        </li>
                    }
                    @for(var pge =pager.StartPage;pge <= pager.EndPage;pge++)
                    {
                        <li class="page-item" @(pge==pager.CurrentPage? "active" :"")>
                            <a class="page-link"asp-action="Index" asp-controller="RequestOrder" asp-route-pg="@pge">@pge</a>
                        </li>
                    }
                    @if(pager.CurrentPage<pager.TotalPages)
                    {
                       <li class="page-item">
                            <a class="page-link"asp-action="Index" asp-controller="RequestOrder" asp-route-pg="@(pager.CurrentPage+1)">Next</a>
                        </li> 
                        <li class="page-item">
                            <a class="page-link"asp-action="Index" asp-controller="RequestOrder" asp-route-pg="@(pager.TotalPages)">Last</a>
                        </li> 
                    }

                </ul>
            }
        </nav>
    </div>
</div>