E-Commerce Website/Controllers/AdminController.cs
using E_Commerce_Website.DAL.Constant;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace E_Commerce_Website.Controllers
{
    [Authorize(Roles = Roles.adminrole)]
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

E-Commerce Website/Controllers/MenuController.cs
using E_Commerce_Website.BL.IRepositories;
using E_Commerce_Website.BL.Pagination;
using E_Commerce_Website.BL.Repositories;
using E_Commerce_Website.BL.Search;
using E_Commerce_Website.BL.ViewModels;
using E_Commerce_Website.DAL.Constant;
using E_Commerce_Website.DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace E_Commerce_Website.Controllers
{
    [Authorize(Roles = Roles.adminrole)]
    public class MenuController : Controller
    {
        private readonly IServiceProduct serviceproduct;
        private readonly IServiceCategory servicecategory;
        public MenuController(IServiceProduct serviceproduct, IServiceCategory servicecategory)
        {
            this.serviceproduct = serviceproduct;
            this.servicecategory = servicecategory;
        }
        #region all Products
        public async Task<IActionResult> Index(string search,int pg=1)
        {

            var productlist = await serviceproduct.GetallProducts();
            if (search is not null)
            {
                var searchData = Search<Menus>.SearchByName(pg, search, productlist);
                this.ViewBag.Pager = searchData.Item2;
                return View(searchData.Item1);
            }
            var data = Pagination<Menus>.GetPaginationData(pg, productlist);
            this.ViewBag.Pager = data.Item2;
            return View(data.Item1);
        }

        #endregion


        #region all deleted product
        [HttpGet]
        public async Task<IActionResult> Deletedproduct(string search,int pg=1)
        {
            var productlistdeleted = await serviceproduct.GetalldeletedProducts();
            if (search is not null)
            {
                var searchData = Search<Menus>.SearchByNameDelete(pg, search, productlistdeleted);
                this.ViewBag.pager = searchData.Item2;
                return View(searchData.Item1);
            }
            var data = Pagination<Menus>.GetPaginationData(pg, productlistdeleted);
            this.ViewBag.pager = data.Item2;
            return View(data.Item1);
        }

        #endregion

        #region all create product
        [HttpGet]
        public async Task<IActionResult> CreateProducts()
        {
            var list = await servicecategory.GetallCategories();
            ViewBag.list = list;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateProducts(ProductViewModel productViewModel)
        {

            if (ModelState.IsValid)
            {
                var name = User.Identity.Name;
                var result = await serviceproduct.add(productViewModel,name);
                return RedirectToAction("Index");
            }
            var list = await servicecategory.GetallCategories();
            ViewBag.list = list;
            return View(productViewModel);
        }

        #endregion

        #region all updated product

        [HttpGet]
        public async Task<IActionResult> UpdateProduct(int Id)
        {
            var result = await serviceproduct.GetByid(Id);
            var list = await servicecategory.GetallCategories();
            ViewBag.list = list;
            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public  IActionResult UpdateProduct(ProductUpdateViewModel productUpdateViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var name = User.Identity.Name;
                    serviceproduct.Update(productUpdateViewModel,name);
                    return RedirectToAction("Index");
                }
                catch (ArgumentNullException)
                {
                    ModelState.AddModelError("Name", "Updated Name Already exist in Menus or Restor it from Deleted Menus");
                }

            }
            var list =  servicecategory.GetallCategories();
            ViewBag.list = list;
            return View(productUpdateViewModel);
        }

        #endregion

        #region  deleted product

        [HttpGet]
        public async Task<IActionResult> DeleteProduct(int Id)
        {
            var name = User.Identity.Name;
            await serviceproduct.Delete(Id,name);
            return RedirectToAction("Index");
        }

        #endregion


        #region restore product

        [HttpGet]
        public async Task<IActionResult> RestoreProduct(int Id)
        {
            var name = User.Identity.Name;
            await serviceproduct.RestoreProduct(Id,name);
            return RedirectToAction("Deletedproduct");
        }

        #endregion
    }
}

E-Commerce Website/Views/Menu/CreateProducts.cshtml
@model ProductViewModel
@{
    ViewData["Title"] = "Create";
    Layout = "_AdminLayout";
    SelectList categorylist = new SelectList(ViewBag.list, "Id", "Name");
}
@section stylecss{
    <style>
        span{
            font-size:14px;
        }
    </style>
}
<section class="form-container">

   <form asp-action="CreateProducts" asp-controller="Menu" enctype="multipart/form-data">
       <div asp-validation-summary="All" class="text-danger" style="font-size:14px;"></div>
       <div class="input-group">
           <label asp-for="Name" style="font-size:15px"></label>
           <input type="text" asp-for="Name" maxlength="25" minlength="5" placeholder="enter name" class="box" autofocus>
       </div>
       <div class="input-group">
           <label asp-for="Price" style="font-size:15px"></label>
           <input type="number" asp-for="Price" min="1" class="box" >
       </div>
       <div class="input-group">
           <label asp-for="Discount" style="font-size:15px"></label>
           <input type="number" asp-for="Discount" min="1" class="box" >
       </div>
       <div class="input-group">
           <label asp-for="Detailes" style="font-size:15px"></label>
           <textarea type="text" asp-for="Detailes" maxlength="100" minlength="5" placeholder="enter detailes" class="box" multiple></textarea>
       </div>
       <div class="input-group">
           <label asp-for="File" style="font-size:15px"></label>
           <input type="file"accept="image/*" asp-for="File" class="box" >
       </div>
        <div class="input-group">
           <label asp-for="File2" style="font-size:15px"></label>
           <input type="file"accept="video/*" asp-for="File2" class="box" >
       </div>
        
       <div class="input-group">
           <label style="font-size:15px;margin:5px 20px 0 0;">Category Name </label>
           <select asp-items="categorylist" asp-for="CategoryId" class="form-select" >
           </select>
       </div>
      
       <input type="submit" value="Create" class="btn btn-success mt-4" name="submit">
   </form>

</section>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

E-Commerce Website/Views/Menu/Deletedproduct.cshtml
@model List< Menus>
@{
    ViewData["Title"] = "Deleted Products";
    Layout = "_AdminLayout";
     Pager pager=new Pager();
    int pageNo=0;
    if(ViewBag.pager is not null)
    {
        pager = ViewBag.pager;
        pageNo = pager.CurrentPage;
    }
}

<div style="margin-top:20px">
            <div class="flex-flow justify-content-start input-group mb-4">
              <a asp-action="Index" asp-controller="Admin" class="btn btn-secondary" style="margin-right:6rem">Back to Dashboard</a>
            </div>
            <div class="flex-flow mb-1">
             <form asp-action="Deletedproduct" method="get">
              <div class="input-group justify-content-end">
                 <div class="form-outline">
                     <input type="search" id="form1" name="search" class="form-control" />
                  </div>
                  <button type="submit" value="search" class="btn btn-primary">
                      <i class="fas fa-search"></i>
                  </button>
                  <a asp-action="Deletedproduct" asp-controller="Menu" class="btn btn-primary" style="margin-left:6rem">Refresh</a>
              </div>
            </form>
            </div>
          

    <div id="content" >
        <table class="table table-bordered mt-3 table-striped table-hover">
            <thead class=" text-center" style="background:#2b6777 ;color:white">
                <tr style="margin:auto">
                     <th>Code</th>
                     <th>Name</th>
                     <th>Price</th>
                     <th>Discount</th>
                     <th>Price After Discount</th>
                     <th>Details</th>
                      <th>Image</th>
                     <th>Video</th>
                     <th>Category Code</th>
                     <th>Is Deleted</th>
                     <th>UserName</th>
                      <th>Create Date</th>
                      <th>Update Date</th>
                      <th>Delete Date</th>
                      <th>Restore Date</th>
                     <th>Options</th>
                 </tr>
             </thead>
             <tbody class="m-1">
               @foreach(var itm in Model)
                {
                    <tr style="margin:auto">
                        <td>@itm.Id</td>
                        <td>@itm.Name</td>
                        <td>@itm.Price</td>
                        <td>@itm.Discount</td>
                        @if(@itm.Discount>0)
                        {
                          <td>@itm.DiscountPrice</td>
                        }
                        else
                        {
                            <td>@itm.Price</td> 
                        }
                       
                        <td>@itm.Detailes</td>
                        <td>
                           <img src="~/uploaded_img/@itm.imgpath" style="width:64px" class="img-thumbnail">
                          </td>
                          <td>
                           <video width="64" height="64" controls loop>
                              <source src="~/uploaded_img/@itm.VideoPath" type="video/mp4">
                           </video>
                          </td>
                        <td>@itm.CategoryId</td>
                        <td>@itm.IsDeleted</td>
                         <td>@itm.UserName</td>
                         <td>@itm.CreateDate</td>
                        <td>@itm.UpdateDate</td>
                        <td>@itm.DeleteDate</td>
                        <td>@itm.RestoreDate</td>
                        <td>
                            <a asp-action="RestoreProduct" id="btn" asp-controller="Menu"asp-route-id="@itm.Id"onclick="return confirm('are you sure to Restore this item @itm.Name')" class="btn btn-danger">Restore</a>
                        </td>
                    </tr>
        
                }
            </tbody>
        </table>
         <nav class="...">
            @if(pager.TotalPages>0)
            {
                <ul class="pagination justify-content-center pagination-lg">
                    @if(pager.CurrentPage>1)
                    {
                        <li class="page-item">
                            <a class="page-link"asp-action="Deletedproduct" asp-controller="Menu" asp-route-pg="1">Frist</a>
                        </li>  
                        <li>
                            <a class="page-link"asp-action="Deletedproduct" asp-controller="Menu" asp-route-pg="@(pager.CurrentPage-1)">Previous</a>
                        </li>
                    }
                    @for(var pge =pager.StartPage;pge <= pager.EndPage;pge++)
                    {
                        <li class="page-item" @(pge==pager.CurrentPage? "active" :"")>
                            <a class="page-link"asp-action="Deletedproduct" asp-controller="Menu" asp-route-pg="@pge">@pge</a>
                        </li>
                    }
                    @if(pager.CurrentPage<pager.TotalPages)
                    {
                       <li class="page-item">
                            <a class="page-link"asp-action="Deletedproduct" asp-controller="Menu" asp-route-pg="@(pager.CurrentPage+1)">Next</a>
                        </li> 
                        <li class="page-item">
                            <a class="page-link"asp-action="Deletedproduct" asp-controller="Menu" asp-route-pg="@(pager.TotalPages)">Last</a>
                        </li> 
                    }

                </ul>
            }
        </nav>
    </div>
</div>

E-Commerce Website/Views/Menu/Index.cshtml
@model List< Menus>
@{
    ViewData["Title"] = "Products";
    Layout = "_AdminLayout";
     Pager pager=new Pager();
    int pageNo=0;
    if(ViewBag.Pager is not null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}

<div style="margin-top:20px">
            <div class="flex-flow justify-content-start input-group">
                 <a asp-action="Index" asp-controller="Admin" class="btn btn-secondary m-3">Back to Dashboard</a>
                 <a asp-action="CreateProducts" asp-controller="Menu" class="btn btn-success m-3">Create</a>
            </div>
            <div class="flex-flow mb-1">
                   <form asp-action="Index" method="get">
              <div class="input-group justify-content-end flex-flow">
                
                 <div class="form-outline">
                     <input type="search" id="form1" name="search" class="form-control" />
                  </div>
                  <button type="submit" value="search" class="btn btn-primary">
                      <i class="fas fa-search"></i>
                  </button>
                  <a asp-action="Index" asp-controller="Menu" class="btn btn-primary" style="margin-left:6rem">Refresh</a>
              </div>
            </form>  
                </div>
    <div id="content" >
        <table class="table table-bordered mt-3 table-striped table-hover">
            <thead class=" text-center" style="background:#2b6777 ;color:white">
                <tr style="margin:auto">
                    <th>Code</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Discount</th>
                    <th>Price After Discount</th>
                    <th>Detailes</th>
                    <th>Image</th>
                    <th>Video</th>
                    <th>Category Code</th>
                    <th>Is Deleted</th>
                    <th>UserName</th>
                    <th>Create Date</th>
                    <th>Update Date</th>
                    <th>Delete Date</th>
                    <th>Restore Date</th>
                    <th>Options</th>
                </tr>
             </thead>
             <tbody class="m-1">
               @foreach(var itm in Model)
                {
                    <tr style="margin:auto">
                        <td>@itm.Id</td>
                        <td>@itm.Name</td>
                        <td>@itm.Price</td>
                        <td>@itm.Discount</td>
                        @if(@itm.Discount>0)
                        {
                          <td>@itm.DiscountPrice</td>
                        }
                        else
                        {
                            <td>@itm.Price</td> 
                        }
                        <td>@itm.Detailes</td>
                        <td>
                            <img src="~/uploaded_img/@itm.imgpath" style="width:64px" class="img-thumbnail">
                        </td>
                        <td>
                            <video width="64" height="64" controls loop>
                              <source src="~/uploaded_img/@itm.VideoPath" type="video/mp4">
                           </video>
                        </td>                     
                        <td>@itm.CategoryId</td>
                        <td>@itm.IsDeleted</td>
                        <td>@itm.UserName</td>
                        <td>@itm.CreateDate</td>
                        <td>@itm.UpdateDate</td>
                        <td>@itm.DeleteDate</td>
                        <td>@itm.RestoreDate</td>
                        <td>
                            <a asp-action="UpdateProduct" id="btn" asp-controller="Menu" asp-route-id="@itm.Id" class="btn btn-secondary m-1">Edit</a>
                            <a asp-action="DeleteProduct" id="btn" asp-controller="Menu" asp-route-id="@itm.Id" onclick="return confirm('are you sure to delete this item @itm.Name')" class="btn btn-danger m-1">Delete</a>
                        </td>

                    </tr>
        
                }
            </tbody>
        </table>
           <nav class="...">
            @if(pager.TotalPages>0)
            {
                <ul class="pagination justify-content-center pagination-lg">
                    @if(pager.CurrentPage>1)
                    {
                        <li class="page-item">
                            <a class="page-link"asp-action="Index" asp-controller="Menu" asp-route-pg="1">Frist</a>
                        </li>  
                        <li>
                            <a class="page-link"asp-action="Index" asp-controller="Menu" asp-route-pg="@(pager.CurrentPage-1)">Previous</a>
                        </li>
                    }
                    @for(var pge =pager.StartPage;pge <= pager.EndPage;pge++)
                    {
                        <li class="page-item" @(pge==pager.CurrentPage? "active" :"")>
                            <a class="page-link"asp-action="Index" asp-controller="Menu" asp-route-pg="@pge">@pge</a>
                        </li>
                    }
                    @if(pager.CurrentPage<pager.TotalPages)
                    {
                       <li class="page-item">
                            <a class="page-link"asp-action="Index" asp-controller="Menu" asp-route-pg="@(pager.CurrentPage+1)">Next</a>
                        </li> 
                        <li class="page-item">
                            <a class="page-link"asp-action="Index" asp-controller="Menu" asp-route-pg="@(pager.TotalPages)">Last</a>
                        </li> 
                    }

                </ul>
            }
        </nav>
    </div>
</div>

E-Commerce Website/Views/Menu/UpdateProduct.cshtml
@model ProductUpdateViewModel
@{
    ViewData["Title"] = "Update";
    Layout = "_AdminLayout";
    SelectList categorylist = new SelectList(ViewBag.list, "Id", "Name");
}
@section stylecss{
    <style>
        span{
            font-size:14px;
        }
    </style>
}
<section class="form-container">

   <form asp-action="UpdateProduct" asp-controller="Menu" enctype="multipart/form-data">
       <div asp-validation-summary="All" class="text-danger" style="font-size:14px;"></div>
       <input type="hidden" asp-for="Id" />
       <div class="input-group">
           <label asp-for="Name" style="font-size:15px"></label>
           <input type="text" asp-for="Name" maxlength="25" minlength="5" placeholder="enter name" class="box" autofocus>
       </div>
       <div class="input-group">
           <label asp-for="Price" style="font-size:15px"></label>
           <input type="number" asp-for="Price" min="1" class="box" >
       </div>
       <div class="input-group">
           <label asp-for="Discount" style="font-size:15px"></label>
           <input type="number" asp-for="Discount" min="1" class="box" >
       </div>
       <div class="input-group">
           <label asp-for="Detailes" style="font-size:15px"></label>
           <textarea type="text" asp-for="Detailes" maxlength="100" minlength="5" placeholder="enter detailes" class="box"></textarea>
       </div>
       <div class="input-group">
           <label asp-for="File" style="font-size:15px"></label>
           <input type="file"accept="image/*"  asp-for="File" class="box" >
           @if(@Model.imgpath1!=null)
            
                {
                    <img src="~/uploaded_img/@Model.imgpath1" style="width:124px" class="img-thumbnail" />
                }
       </div>
       <div class="input-group">
           <label asp-for="File2" style="font-size:15px"></label>
           <input type="file"accept="video/*"  asp-for="File2" class="box" >
           @if(@Model.VideoPath!=null)
            
                {
                    <video width="64" height="64" controls loop>
                        <source src="~/uploaded_img/@Model.VideoPath" type="video/mp4">
                    </video>
                }
       </div>
       <div class="input-group">
           <label style="font-size:15px;margin:5px 20px 0 0;">Category Name </label>
           <select asp-items="categorylist" asp-for="CategoryId" class="form-select" >
           </select>
       </div>
      
       <input type="submit" value="Update" class="btn btn-success mt-4" name="submit">
   </form>

</section>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}